
export const coffees = [
    {
        id: 1,
        name: "Expresso Tradicional",
        src: 'src/assets/coffees/Type=Expresso.png',
        description: "O tradicional café feito com água quente e grãos moídos",
        price: 9.90,
        tags: ["Tradicional"],
       }   ,
    {
        id: 2,
        name: "Expresso Americano",
        src: 'src/assets/coffees/Type=Americano.png',
        description: "Expresso diluído, menos intenso que o tradicional",
        price: 9.90,
        tags: ["Tradicional"],
       }   , {
        id: 3,
        name: "Expresso Cremoso",
        src: 'src/assets/coffees/Type=Expresso Cremoso.png',
        description: "Café expresso tradicional com espuma cremosa",
        price: 9.90,
        tags: ["Tradicional"],
       }   , {
        id: 4,
        name: "Expresso Gelado",
        src: 'src/assets/coffees/Type=Café Gelado.png',
        description: "Bebida preparada com café expresso e cubos de gelo",
        price: 9.90,
        tags: ["Tradicional", "Gelado"],	
       }   , {
        id: 5,
        name: "Café com Leite",
        src: 'src/assets/coffees/Type=Café com Leite.png',
        description: "Meio a meio de expresso tradicional com leite vaporizado",
        price: 9.90,
        tags: ["Tradicional", "Com Leite"],
       }   , {
        id: 6,
        name: "Latte",
        src: 'src/assets/coffees/Type=Latte.png',
        description: "Uma dose de café expresso com o dobro de leite e espuma cremosa",
        price: 9.90,
        tags: ["Tradicional", "Com Leite"],
       }   , {
        id: 7,
        name: "Capuccino",
        src: 'src/assets/coffees/Type=Capuccino.png',
        description: "Bebida com canela feita de doses iguais de café, leite e espuma",
        price: 9.90,
        tags: ["Tradicional", "Com Leite"],
       }   , {
        id: 8,
        name: "Macchiato",
        src: 'src/assets/coffees/Type=Macchiato.png',
        description: "Café expresso misturado com um pouco de leite quente e espuma",
        price: 9.90,
        tags: ["Tradicional", "Com Leite"],
       }   , {
        id: 9,
        name: "Mochaccino",
        src: 'src/assets/coffees/Type=Mochaccino.png',
        description: "Café expresso com calda de chocolate, pouco leite e espuma",
        price: 9.90,
        tags: ["Tradicional", "Com Leite"],
       }   , {
        id: 10,
        name: "Chocolate Quente",
        src: 'src/assets/coffees/Type=Chocolate Quente.png',
        description: "Bebida feita com chocolate dissolvido no leite quente e café",
        price: 9.90,
        tags: ["Especial", "Com Leite"],
       }   , {
        id: 11,
        name: "Cubano",
        src: 'src/assets/coffees/Type=Cubano.png',
        description: "Drink gelado de café expresso com rum, creme de leite e hortelã",
        price: 9.90,
        tags: ["Especial", "Alcoólico", "Gelado"],
       }   , {
        id: 12,
        name: "Havaiano",
        src: 'src/assets/coffees/Type=Havaiano.png',
        description: "Bebida adocicada preparada com café e leite de coco",
        price: 9.90,
        tags: ["Especial"],
       }   , {
        id: 13,
        name: "Árabe",
        src: 'src/assets/coffees/Type=Árabe.png',
        description: "Bebida preparada com grãos de café árabe e especiarias",
        price: 9.90,
        tags: ["Especial"],
       }   , {
        id: 14,
        name: "Irlandês",
        src: 'src/assets/coffees/Type=Irlandês.png',
        description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
        price: 9.90,
        tags: ["Especial", "Alcoólico"],	
       }
    
];